-- Seed: Power BI Dashboards - Données de démo
-- Script pour insérer les 5 dashboards initiaux avec leurs KPIs

-- Assurez-vous que vous avez un utilisateur auth pour author_id
-- Remplacez '00000000-0000-0000-0000-000000000000' par un UUID valide si nécessaire

-- Dashboard 1: Analyse des Stocks
INSERT INTO public.powerbi_dashboards (
  id,
  slug,
  title,
  description,
  long_description,
  topic,
  sub_topics,
  personas,
  complexity,
  visualization_types,
  powerbi_version,
  data_sources,
  thumbnail_url,
  screenshots,
  pbix_file_url,
  pbit_file_url,
  documentation_url,
  views,
  downloads,
  rating,
  rating_count,
  published,
  featured,
  published_at,
  created_at,
  updated_at,
  dax_measures,
  use_cases,
  installation_guide,
  author_id
) VALUES (
  gen_random_uuid(),
  'analyse-stocks-comptabilite',
  'Analyse des Stocks - Comptabilité',
  'Dashboard complet pour analyser la rotation, l''obsolescence et la valorisation des stocks avec alertes automatiques.',
  'Ce dashboard Power BI offre une vue complète de votre gestion de stock avec des indicateurs clés pour optimiser votre trésorerie et réduire les coûts.',
  'comptabilite',
  ARRAY['stocks', 'grand-livre'],
  ARRAY['Expert-Comptable', 'Contrôleur de Gestion', 'DAF'],
  'intermediaire',
  ARRAY['kpi-cards', 'line-charts', 'bar-charts', 'tables', 'waterfall', 'gauge'],
  'Power BI Desktop - Version Octobre 2024 ou supérieure',
  ARRAY['SQL Server', 'Excel', 'SAP'],
  '/images/dashboards/stocks-thumb.jpg',
  ARRAY['/images/dashboards/stocks-1.jpg', '/images/dashboards/stocks-2.jpg'],
  '/files/dashboards/analyse-stocks.pbix',
  '/files/dashboards/analyse-stocks.pbit',
  '/files/dashboards/analyse-stocks-doc.pdf',
  2847,
  456,
  4.6,
  89,
  true,
  true,
  '2024-09-15T10:00:00Z',
  '2024-09-10T08:00:00Z',
  '2024-09-20T14:30:00Z',
  '[
    {"name": "Rotation Stock", "formula": "DIVIDE([Coût des ventes], [Stock moyen], 0)", "description": "Mesure le nombre de fois où le stock est renouvelé par an"},
    {"name": "Jours de Stock", "formula": "365 / [Rotation Stock]", "description": "Nombre de jours moyen de détention du stock"},
    {"name": "Stock Mort", "formula": "CALCULATE([Valeur Stock], FILTER(Stocks, Stocks[DernierMouvement] < TODAY() - 180))", "description": "Valeur du stock sans mouvement depuis plus de 180 jours"}
  ]'::jsonb,
  ARRAY['Réduire le working capital de 15-20%', 'Identifier les produits en surstock', 'Optimiser les commandes fournisseurs'],
  'Installation: 1. Télécharger le fichier .pbix, 2. Ouvrir avec Power BI Desktop, 3. Configurer la source de données',
  '00000000-0000-0000-0000-000000000000'
);

-- Dashboard 2: Valorisation d'Entreprise
INSERT INTO public.powerbi_dashboards (
  id,
  slug,
  title,
  description,
  topic,
  sub_topics,
  personas,
  complexity,
  visualization_types,
  powerbi_version,
  data_sources,
  views,
  downloads,
  rating,
  rating_count,
  published,
  featured,
  published_at,
  created_at,
  updated_at,
  dax_measures,
  use_cases,
  author_id
) VALUES (
  gen_random_uuid(),
  'valorisation-entreprise-finance',
  'Valorisation d''Entreprise DCF & Multiples',
  'Dashboard avancé pour la valorisation d''entreprise par DCF, multiples comparables et analyse de sensibilité.',
  'finance',
  ARRAY['valorisation', 'rentabilite', 'cashflow'],
  ARRAY['CFO', 'Directeur Financier', 'Analyste Financier'],
  'avance',
  ARRAY['kpi-cards', 'waterfall', 'scatter', 'tables', 'gauge', 'donut'],
  'Power BI Desktop - Version Octobre 2024 ou supérieure',
  ARRAY['Excel', 'SQL Server', 'Azure'],
  1923,
  234,
  4.8,
  45,
  true,
  true,
  '2024-08-20T10:00:00Z',
  '2024-08-15T08:00:00Z',
  '2024-09-01T14:30:00Z',
  '[
    {"name": "EV", "formula": "[Market Cap] + [Dette nette] - [Trésorerie]", "description": "Valeur d''entreprise"},
    {"name": "Multiple EBITDA", "formula": "DIVIDE([EV], [EBITDA], BLANK())", "description": "Multiple de valorisation EV/EBITDA"}
  ]'::jsonb,
  ARRAY['Valorisation pre-exit ou M&A', 'Due diligence financière', 'Présentation investisseurs'],
  '00000000-0000-0000-0000-000000000000'
);

-- Dashboard 3: Pipeline Commercial
INSERT INTO public.powerbi_dashboards (
  id,
  slug,
  title,
  description,
  topic,
  sub_topics,
  personas,
  complexity,
  visualization_types,
  data_sources,
  views,
  downloads,
  rating,
  rating_count,
  published,
  featured,
  published_at,
  created_at,
  updated_at,
  dax_measures,
  use_cases,
  author_id
) VALUES (
  gen_random_uuid(),
  'pipeline-commercial-sales',
  'Pipeline Commercial & Forecast',
  'Suivi complet du pipeline commercial avec forecast pondéré, analyse des opportunités et performance par vendeur.',
  'sales',
  ARRAY['pipeline', 'performance', 'geo'],
  ARRAY['Directeur Commercial', 'Sales Manager'],
  'intermediaire',
  ARRAY['kpi-cards', 'funnel', 'bar-charts', 'line-charts', 'tables'],
  ARRAY['Salesforce', 'HubSpot', 'SQL Server'],
  3421,
  678,
  4.7,
  142,
  true,
  false,
  '2024-09-01T10:00:00Z',
  '2024-08-25T08:00:00Z',
  '2024-09-15T14:30:00Z',
  '[
    {"name": "Win Rate", "formula": "DIVIDE(CALCULATE(COUNT(Opportunités[ID]), Opportunités[Statut] = \"Won\"), COUNT(Opportunités[ID]), 0)", "description": "Taux de conversion des opportunités"},
    {"name": "Forecast Pondéré", "formula": "SUMX(Opportunités, Opportunités[Montant] * Opportunités[Probabilité %])", "description": "Prévision de CA pondérée"}
  ]'::jsonb,
  ARRAY['Prévision de CA mensuel', 'Coaching des équipes commerciales', 'Identification des deals à risque'],
  '00000000-0000-0000-0000-000000000000'
);

-- Dashboard 4: Performance Marketing
INSERT INTO public.powerbi_dashboards (
  id,
  slug,
  title,
  description,
  topic,
  sub_topics,
  personas,
  complexity,
  visualization_types,
  data_sources,
  views,
  downloads,
  rating,
  rating_count,
  published,
  published_at,
  created_at,
  updated_at,
  dax_measures,
  use_cases,
  author_id
) VALUES (
  gen_random_uuid(),
  'performance-campagnes-marketing',
  'Performance Campagnes Marketing - ROI & CAC',
  'Analysez le ROI de vos campagnes marketing, le CAC par canal et l''attribution multi-touch.',
  'marketing',
  ARRAY['campagnes', 'funnel', 'seo'],
  ARRAY['CMO', 'Marketing Manager', 'Growth Hacker'],
  'intermediaire',
  ARRAY['kpi-cards', 'funnel', 'treemap', 'line-charts', 'sankey'],
  ARRAY['Google Analytics', 'Facebook Ads', 'Google Ads', 'HubSpot'],
  2156,
  389,
  4.5,
  78,
  true,
  '2024-08-10T10:00:00Z',
  '2024-08-01T08:00:00Z',
  '2024-08-25T14:30:00Z',
  '[
    {"name": "ROAS", "formula": "DIVIDE([Revenus générés], [Dépenses publicitaires], 0)", "description": "Return on Ad Spend"},
    {"name": "CAC", "formula": "DIVIDE([Coûts Marketing totaux], [Nouveaux clients], 0)", "description": "Coût d''acquisition client"}
  ]'::jsonb,
  ARRAY['Optimiser le mix marketing', 'Réduire le CAC', 'Identifier les meilleurs canaux'],
  '00000000-0000-0000-0000-000000000000'
);

-- Dashboard 5: Tableau de Bord CFO
INSERT INTO public.powerbi_dashboards (
  id,
  slug,
  title,
  description,
  topic,
  sub_topics,
  personas,
  complexity,
  visualization_types,
  data_sources,
  views,
  downloads,
  rating,
  rating_count,
  published,
  featured,
  published_at,
  created_at,
  updated_at,
  dax_measures,
  use_cases,
  author_id
) VALUES (
  gen_random_uuid(),
  'tableau-bord-cfo-finance',
  'Tableau de Bord CFO - P&L & Cash Flow',
  'Dashboard exécutif pour CFO avec P&L waterfall, cash flow bridge, KPIs financiers et rolling forecast.',
  'finance',
  ARRAY['rentabilite', 'cashflow', 'budget'],
  ARRAY['CFO', 'Directeur Financier', 'Contrôleur de Gestion'],
  'avance',
  ARRAY['kpi-cards', 'waterfall', 'line-charts', 'bar-charts', 'gauge'],
  ARRAY['SAP', 'Oracle', 'SQL Server', 'Excel'],
  4521,
  892,
  4.9,
  187,
  true,
  true,
  '2024-07-15T10:00:00Z',
  '2024-07-01T08:00:00Z',
  '2024-09-01T14:30:00Z',
  '[
    {"name": "EBITDA", "formula": "[Revenus] - [Coûts opérationnels]", "description": "Résultat opérationnel avant amortissements"},
    {"name": "Marge EBITDA %", "formula": "DIVIDE([EBITDA], [Revenus], 0)", "description": "Marge opérationnelle"},
    {"name": "Free Cash Flow", "formula": "[EBITDA] - [Capex] - [Variation Working Capital] - [Impôts]", "description": "Flux de trésorerie disponible"}
  ]'::jsonb,
  ARRAY['Reporting COMEX mensuel', 'Présentation investisseurs', 'Pilotage financier global'],
  '00000000-0000-0000-0000-000000000000'
);

-- Optionnel: Insérer quelques KPIs pour le premier dashboard
-- Note: Remplacer le dashboard_id par l'UUID réel après insertion
-- INSERT INTO public.dashboard_kpis (dashboard_id, name, description, formula, display_order)
-- SELECT id, 'Valeur totale du stock', 'Valorisation totale du stock au coût d''achat', 'SUM(Stocks[ValeurStock])', 1
-- FROM public.powerbi_dashboards WHERE slug = 'analyse-stocks-comptabilite';
