-- Create table for storing article sections (sectional generation approach)
-- This solves the truncation issue by storing each section individually

CREATE TABLE IF NOT EXISTS articles_content (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  job_id TEXT NOT NULL,
  section_index INTEGER NOT NULL,
  section_id TEXT,
  section_title TEXT,
  content JSONB NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(job_id, section_index)
);

-- Index for fast lookups by job_id
CREATE INDEX IF NOT EXISTS idx_articles_content_job_id ON articles_content(job_id);

-- Index for ordering by section_index
CREATE INDEX IF NOT EXISTS idx_articles_content_job_section ON articles_content(job_id, section_index);

-- Enable Row Level Security
ALTER TABLE articles_content ENABLE ROW LEVEL SECURITY;

-- Policy: Allow service role full access
CREATE POLICY "Service role full access" ON articles_content
  FOR ALL
  USING (auth.role() = 'service_role');

-- Policy: Allow authenticated users to read
CREATE POLICY "Authenticated users can read" ON articles_content
  FOR SELECT
  USING (auth.role() = 'authenticated');

COMMENT ON TABLE articles_content IS 'Stores individual article sections generated by GPT-5.1. Each section is stored separately to avoid truncation issues with large payloads.';
COMMENT ON COLUMN articles_content.job_id IS 'References the workflow job that generated this section';
COMMENT ON COLUMN articles_content.section_index IS 'Order of the section in the article (0-based)';
COMMENT ON COLUMN articles_content.section_id IS 'Unique identifier for the section (e.g., "intro", "section-1")';
COMMENT ON COLUMN articles_content.content IS 'JSONB containing section HTML, metadata, and other details';
